#pragma once

#define AIRGUARD_WIFI_SSID "YOUR_WIFI_SSID"
#define AIRGUARD_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define AIRGUARD_MQTT_HOST "192.168.50.46"
#define AIRGUARD_MQTT_PORT 1883
#define AIRGUARD_MQTT_USER ""
#define AIRGUARD_MQTT_PASSWORD ""
